# Generated by Django 5.2.4 on 2025-08-30 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='class',
            name='class_group',
            field=models.CharField(choices=[('pre', 'Pre-Primary'), ('1-5', 'Primary'), ('6-10', 'Secondary')], default=1, max_length=10),
            preserve_default=False,
        ),
    ]
