# Generated by Django 5.2.4 on 2025-09-12 17:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0001_initial'),
        ('students', '0003_class_class_group'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AcademicYear',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, unique=True)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('is_active', models.BooleanField(default=False)),
                ('is_current', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['-start_date'],
            },
        ),
        migrations.RemoveField(
            model_name='bulkuploadjob',
            name='uploaded_by',
        ),
        migrations.AlterUniqueTogether(
            name='mark',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='mark',
            name='entered_by',
        ),
        migrations.RemoveField(
            model_name='mark',
            name='exam',
        ),
        migrations.RemoveField(
            model_name='mark',
            name='student',
        ),
        migrations.RemoveField(
            model_name='mark',
            name='subject',
        ),
        migrations.RemoveField(
            model_name='result',
            name='student',
        ),
        migrations.AlterUniqueTogether(
            name='teacherclass',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='teacherclass',
            name='class_assigned',
        ),
        migrations.RemoveField(
            model_name='teacherclass',
            name='teacher',
        ),
        migrations.AlterModelOptions(
            name='exam',
            options={'ordering': ['exam_type', 'order']},
        ),
        migrations.AlterUniqueTogether(
            name='subject',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='exam',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='exam',
            name='order',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='subject',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='exam',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='subject',
            name='code',
            field=models.CharField(max_length=10, unique=True),
        ),
        migrations.CreateModel(
            name='ClassSubjectMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_main_subject', models.BooleanField(default=True)),
                ('academic_year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assessments.academicyear')),
                ('student_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='students.class')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assessments.subject')),
            ],
        ),
        migrations.CreateModel(
            name='GradeScale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_group', models.CharField(max_length=10)),
                ('exam_type', models.CharField(max_length=2)),
                ('min_marks', models.IntegerField()),
                ('max_marks', models.IntegerField()),
                ('grade', models.CharField(max_length=2)),
                ('grade_point', models.DecimalField(decimal_places=1, max_digits=4)),
            ],
            options={
                'ordering': ['class_group', 'exam_type', '-min_marks'],
                'unique_together': {('class_group', 'exam_type', 'min_marks', 'max_marks')},
            },
        ),
        migrations.CreateModel(
            name='StudentExamSummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_marks_obtained', models.DecimalField(decimal_places=2, default=0, max_digits=7)),
                ('total_max_marks', models.IntegerField(default=0)),
                ('percentage', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('overall_grade', models.CharField(blank=True, max_length=2)),
                ('overall_grade_point', models.DecimalField(decimal_places=1, default=0, max_digits=4)),
                ('class_rank', models.IntegerField(blank=True, null=True)),
                ('subjects_count', models.IntegerField(default=0)),
                ('computed_at', models.DateTimeField(auto_now=True)),
                ('academic_year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assessments.academicyear')),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assessments.exam')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='students.studentprofile')),
            ],
        ),
        migrations.CreateModel(
            name='StudentMark',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marks_obtained', models.DecimalField(decimal_places=2, max_digits=5)),
                ('max_marks', models.IntegerField()),
                ('grade', models.CharField(blank=True, max_length=2)),
                ('grade_point', models.DecimalField(decimal_places=1, default=0, max_digits=4)),
                ('is_absent', models.BooleanField(default=False)),
                ('entered_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('academic_year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assessments.academicyear')),
                ('entered_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assessments.exam')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='students.studentprofile')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assessments.subject')),
            ],
        ),
        migrations.DeleteModel(
            name='AuditLog',
        ),
        migrations.DeleteModel(
            name='BulkUploadJob',
        ),
        migrations.DeleteModel(
            name='Mark',
        ),
        migrations.DeleteModel(
            name='Result',
        ),
        migrations.DeleteModel(
            name='TeacherClass',
        ),
        migrations.RemoveField(
            model_name='subject',
            name='class_assigned',
        ),
        migrations.RemoveField(
            model_name='subject',
            name='is_optional',
        ),
        migrations.AddIndex(
            model_name='classsubjectmapping',
            index=models.Index(fields=['student_class', 'academic_year'], name='assessments_student_efd1ae_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='classsubjectmapping',
            unique_together={('student_class', 'subject', 'academic_year')},
        ),
        migrations.AddIndex(
            model_name='studentexamsummary',
            index=models.Index(fields=['exam', 'academic_year'], name='assessments_exam_id_cc44f7_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='studentexamsummary',
            unique_together={('student', 'exam', 'academic_year')},
        ),
        migrations.AddIndex(
            model_name='studentmark',
            index=models.Index(fields=['student', 'exam', 'academic_year'], name='assessments_student_1c000b_idx'),
        ),
        migrations.AddIndex(
            model_name='studentmark',
            index=models.Index(fields=['exam', 'academic_year'], name='assessments_exam_id_bbc01c_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='studentmark',
            unique_together={('student', 'subject', 'exam', 'academic_year')},
        ),
    ]
